#' ---
#' title: "TMB Stage 1 Helpers"
#' description: "Helper functions to compile and interface with Template Model Builder (TMB) C++ code."
#' ---

#' Compile and load the TMB C++ model for Stage 1.
#'
#' This function checks if the TMB dynamic library exists and is up-to-date with
#' its source `.cpp` file. If not, it triggers a compilation. Finally, it loads
#' the compiled library into the R session if it isn't already loaded.
#'
#' @return The name of the loaded DLL (invisibly).
ensure_tmb_stage1_dll <- function() {

  if (!requireNamespace("TMB", quietly = TRUE)) {
    stop("The `TMB` package is required for the `tmb` backend.")
  }

  cpp_base <- file.path("src", "tmb_stage1_gaussian")
  cpp_file <- paste0(cpp_base, ".cpp")
  dll_file <- TMB::dynlib(cpp_base)
  dll_name <- basename(cpp_base)

  needs_compile <- !file.exists(dll_file) || file.mtime(dll_file) < file.mtime(cpp_file)
  if (needs_compile) {
    TMB::compile(cpp_file)
  }

  loaded_names <- names(getLoadedDLLs())
  if (!(dll_name %in% loaded_names)) {
    dyn.load(dll_file)
  }

  invisible(dll_name)
}

#' Prepare data structure for TMB.
#'
#' This converts a list of cluster-level data frames into the flat, indexed
#' arrays that TMB expects in its C++ template.
#'
#' @param cluster_objects List of precomputed cluster lists.
#' @return A list containing flattened `y`, `z`, and integer vectors for 
#'         `cluster_start` and `cluster_size`.
make_tmb_stage1_data <- function(cluster_objects) {
  ordered <- unname(cluster_objects)
  cluster_size <- vapply(ordered, `[[`, integer(1), "n")
  cluster_start <- cumsum(c(0L, head(cluster_size, -1L)))

  list(
    y = unlist(lapply(ordered, `[[`, "y"), use.names = FALSE),
    z = unlist(lapply(ordered, function(x) x$X[, 2]), use.names = FALSE),
    cluster_start = as.integer(cluster_start),
    cluster_size = as.integer(cluster_size)
  )
}

#' Create the TMB objective function object.
#'
#' This wraps `TMB::MakeADFun` using the data generated by `make_tmb_stage1_data`
#' and initial parameters extracted from a null `lmer` fit.
#'
#' @param cluster_objects List of precomputed cluster lists.
#' @param fit_null An `lmer` object representing the null model (used for starting values).
#' @return A compiled TMB objective function object with methods like `fn()`, `gr()`, and `he()`.
make_tmb_stage1_object <- function(cluster_objects, fit_null) {
  ensure_tmb_stage1_dll()

  data_list <- make_tmb_stage1_data(cluster_objects)
  psi_var <- pack_psi_var(fit_null)
  parameters <- list(
    beta0 = psi_var[[1]],
    beta1 = psi_var[[2]],
    var0 = psi_var[[3]],
    cov01 = psi_var[[4]],
    var1 = psi_var[[5]],
    sigma2 = psi_var[[6]]
  )

  TMB::MakeADFun(
    data = data_list,
    parameters = parameters,
    DLL = "tmb_stage1_gaussian",
    silent = TRUE,
    hessian = TRUE
  )
}

#' Extract or approximate the Hessian from a TMB objective function.
#'
#' @details
#' This helper attempts to use the exact/auto-differentiated Hessian method
#' `he()` if the TMB object provides one. If it is unavailable, it falls back
#' to a numerical approximation via `stats::optimHess()` using the provided
#' objective and gradient functions.
#'
#' @param obj A compiled TMB objective function object, typically returned by
#' `TMB::MakeADFun()`.
#'
#' @return A symmetric numeric matrix representing the Hessian at `obj$par`.
get_tmb_stage1_hessian <- function(obj) {
  if (!is.null(obj$he)) {
    return(unname(as.matrix(obj$he(obj$par))))
  }

  unname(as.matrix(stats::optimHess(par = obj$par, fn = obj$fn, gr = obj$gr)))
}

